name: api
description: FIAS API.
version: 0.0.1
author: Dmitrii Zolotov <dmitrii.zolotov@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  aqueduct: 3.2.1
  postgres: ^1.0.2
  http: ^0.12.0
  uuid: ^2.0.0    # for mongo_dart
  intl: ^0.15.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
